### ISSUE TITLE
Share weights?

### ISSUE THREAD

**Issue by UrosOgrizovic** [oseiskar/autosubsync#11]
Could you provide a link to the model weights, so that inference can be done immediately? Populating csv files and training is just too tedious. :)

**Comment by oseiskar** [comment]
Sure. You can find pre-trained weights (`trained-model.bin`) in the PyPi package https://files.pythonhosted.org/packages/5d/1b/84498777adeaf45a2200936c39240345d32b436bdad337fb953afaf36d41/autosubsync-0.1.4-py2.py3-none-any.whl (the extension is .whl, you can just change it to .zip and extract it normally).

Also note that you do not have to do this if you `pip install autosubsync` and just use the software as-is, without making your own tweaks.
