### ISSUE TITLE
Truncates 1st arg (video filename) when run using bash/sh

### ISSUE THREAD

**Issue by ghost** [oseiskar/autosubsync#20]
in console (debian), this command works fine:

autosubsync [input movie] [input subtitles] [output subs]

for example:
```
autosubsync The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space.avi \
  The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space-out-of-sync-subs.eng.srt \
  The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space-subtitles-synced.eng.srt
```
  
However when scripting in a sh bash script (#!/usr/bin/env bash), the command does not parse args correctly it gives this error:

```
usage: autosubsync [-h] [--max_shift_secs MAX_SHIFT_SECS] [--parallelism PARALLELISM] [--fixed_skew FIXED_SKEW] [--silent] video_file subtitle_file output_file
autosubsync: error: unrecognized arguments: -\ 9\ -\ from\ -\ outer\ -\ space.avi ./The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space-out-of-sync-subs.eng.srt ./The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space-subtitles-synced.eng.srt
Error: Subtitles synchronization failed for './The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space.avi' with subtitles file './The\ IT\ -\ 9\ -\ from\ -\ outer\ -\ space-out-of-sync-subs.eng.srt'.

```
In the sh script, I've tested with command construct:
command="autosubsync \"${video_file}\" \"${subtitle_file}\" \"${output_subtitle_file}\""

${command}

and also tried:
eval ${command}

and even tried with an array command construct:
command=("autosubsync" "\"$video_file\"" "\"$subtitle_file\"" "\"$output_subtitle_file\"")

and even this:
command=("autosubsync" "$video_file" "$subtitle_file" "$output_subtitle_file")

The command construct is correct - copy'n'paste into console works fine, however within the sh script it gives the above error.

**Comment by oseiskar** [comment]
Hi. If it works outside the bash script, that would indicate that the issue is actually in the script and not the autosubsync command. Storing commands with spaces and quotes is tricky in Bash. See here for some solutions / workarounds https://superuser.com/a/360986

**Comment by ghost** [comment]
Yes, I did use the \ method and the array method as well to avoid the quote issue, and even direct command using: autosubsync "${video_file}" "${subtitle_file}" "${output_subtitle_file}"

The script ran the autosubsync command without input errors, but it gives this output instead (this output does not occur when running directly from console, and the --silence option makes no difference to the below output when also used in the scripted command):

```
Extracting audio using ffmpeg and reading subtitles...
stream #1:
  keyframe=1
  duration=0.032
  dts=14.784  pts=14.784
  size=2560
stream #1:
  keyframe=1
......etc.....
00000000  0b 77 04 ff 3f 87 ff e8 d0 01 00 00 00 40 22 00 .w..?........@".
...etc....
000009f0  00 00 00 00 00 00 00 00 00 00 00 02 20 74 ca 74 ............ t.t

error parsing debug value
debug=0
stream #1:320kB time=00:05:09.69 bitrate= 643.3kbits/s speed=25.4x
  keyframe=1
----etc....
000009f0  00 00 00 00 00 00 00 00 00 00 00 02 bd 10 5c 78 ..............\x
size=   55552kB time=00:12:55.58 bitrate= 586.8kbits/s speed=  27x
error parsing debug value
debug=0
size=   56832kB time=00:13:15.84 bitrate= 585.0kbits/s speed=27.3x
error parsing debug value
debug=0
size=   59648kB time=00:13:56.16 bitrate= 584.4kbits/s speed=27.7x
error parsing debug value
debug=0

Enter command: <target>|all <time>|-1 <command>[ <argument>]
```



Then freezes...

**Comment by oseiskar** [comment]
I'm sorry, but if the same arguments work from the command line, then it's an issue in your Bash script and this is something you have to debug yourself. There is nothing special about the argument parsing in autsosubsync that would make it less compatible with Bash than any other program.

However, there's another option that is better suited for scripting: you can try the autosubsync Python API. See example here https://github.com/oseiskar/autosubsync?tab=readme-ov-file#features

**Comment by ghost** [comment]
It has nothing to do with bash scripting. The script runs the autosynsync fine with the correct arguments, but the autosubsync output appears to be using ffmpeg to break apart the video file. The script does not even call ffmpeg.

That's ok, I'll just won't use autosubsync, there are other alternatives that do work. 

Thanks anyhow for your quick response.
