### ISSUE TITLE
Problem to execute train_and_test.sh

### ISSUE THREAD

**Issue by schults** [oseiskar/autosubsync#6]
Hey man, how are you? Everytime I try to execute this script I get this error: 

```
    extract_sound(line['video'], os.path.join(TRAINING_FOLDER, sound_file))
KeyError: 'video'
```

That's part of my csv file:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/23312729/62416159-e4bd0880-b60b-11e9-9ac4-00467aacfa7e.png">

Can you please help me with this?

**Comment by oseiskar** [comment]
Hi! That CSV looks suspicious and has been incorrectly parsed by Excel. Try to open it with a text editor (e.g., Notepad++ or Visual Studo Code) and verify that it is a valid CSV where the first row contains the elements `video`, `subtitles` and `language`, like [this file](https://github.com/oseiskar/autosubsync/blob/master/training/sources.csv.example). Especially count the `"`'s. (your example contains an extra `"` before "subtitles", but that might not be the only issue)
