### ISSUE TITLE
Error: Too few arguments

### ISSUE THREAD

**Issue by Kali0s** [oseiskar/autosubsync#7]
When I try to sync some subtitles with a video, it says "autosubsync: error: Too few arguments", I would be grateful if you could tell what am I doing wrong. Thanks.
![Screenshot_1](https://user-images.githubusercontent.com/53921253/62743528-12a6b080-ba43-11e9-9651-c3ef1ed7d27f.png)

**Comment by oseiskar** [comment]
Hi! You seem to have some trouble with command line arguments in general. I tried to Google for a document that would explain the basics clearly without going too deep into shell scripting, but that was surprisingly difficult (maybe [this one](https://www.w3resource.com/linux-system-administration/commands-and-arguments.php) was the closest to what I was looking for) so here's a very short introduction.

**Command line arguments are separated by whitespace**, *not* backslashes, e.g.,

    autosubsync video.mp4 subs.srt synced.srt

  (you're trying to use the backslash, like `autosubsync video.mp4\subs.srt\synced.srt`, which is incorrect).

**If there are spaces in the file name or path, put it in quotes**, for example,

    autosubsync "folder name/video.mp4" 'folder name/subs.srt' another_folder/synced.srt

Either single-quotes or double-quotes can be used like in the above example.

**...or...** An alternative way of doing this is using backslashes to escape the whitespace

    autosubsync folder\ name/video.mp4 folder\ name/subs.srt another_folder/synced.srt

**Comment by Kali0s** [comment]
Thanks for your help. I figured that backslashes were wrong after reading again the "Usage" section of your post, so I tried again and it seemed to be working nicely until at the end of the sync it said "WARNING: low quality of fit. Wrong subtitle file?", and, of course, the subtitles didn't fit the video. I'd really thank you if you could help me with this issue, and thanks with helping me earlier, I'm not quite used to using  command line arguments.
![Screenshot_1](https://user-images.githubusercontent.com/53921253/62766771-82dd2280-ba93-11e9-85e9-08771ef459a6.png)

**Comment by oseiskar** [comment]
There's unfortunately very little I can do if the subtitles were not synced correctly. This program has certain limitations. For example, if there are any "commercial breaks" that cause the optimal time shift to be different in different parts of the video, this program cannot really handle the situation

**Comment by Kali0s** [comment]
I guess there are several things in the video that can make the program fail. I'll just subtitle the videos manually. Thanks a lot anyways.
